version: "3"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
    - './data:/data/db'
  
  api:
    build: .
    image: chat-app
    restart: always
    depends_on:
      - mongodb
    ports:
      - 3000:3000

